name: ImmortalWrt-CI-test

on:
  workflow_dispatch:

jobs:
  build_openwrt:
    name: Build OpenWrt firmware
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: master

    - name: Get tags
      run : |
        git fetch --tags https://github.com/immortalwrt/immortalwrt.git
        git push --tags
        echo "tag=$(git tag | sort | tail -1)" >> $GITHUB_ENV

    - name: Checkout to tag
      uses: actions/checkout@v4
      with:
        ref: ${{ env.tag }}

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        set +e
        docker rmi `docker images -q`
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /usr/local/lib/android \
          /opt/ghc \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge azure-cli* docker* ghc* zulu* hhvm* llvm* firefox* google* dotnet* aspnetcore* powershell* openjdk* adoptopenjdk* mysql* php* mongodb* moby* snap* || true
        sudo -E apt-get update
        sudo -E apt-get -y install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev qemu-img
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean

    - name: Add Patch
      run: |
        # wget -O $(ls -d ./target/linux/x86/patches-*)/600-bnx2x-warpcore-8727-2g5.patch https://raw.githubusercontent.com/JAMESMTL/snippets/master/bnx2x/patches/bnx2x_warpcore_8727_2_5g_sgmii_txfault.patch
        # wget -O ./package/network/utils/iptables/patches/600-fix-among-match.patch https://git.netfilter.org/iptables/patch/?id=eddbb27651b93ac6f329bf8113223e7360ea7613

    - name: Git Clone
      run: |
        git clone https://github.com/kingyond/luci-app-accesscontrol-plus package/luci/luci-app-accesscontrol-plus
        git clone https://github.com/rufengsuixing/luci-app-adguardhome package/luci/luci-app-adguardhome
        git clone https://github.com/sirpdboy/luci-app-autotimeset package/luci/luci-app-autotimeset
        git clone https://github.com/selfcan/luci-app-homebox package/luci/luci-app-homebox
        git clone https://github.com/riverscn/openwrt-iptvhelper package/luci/luci-app-iptvhelper
        git clone https://github.com/zijieKwok/luci-app-oaf package/luci/luci-app-oaf
        # git clone https://github.com/khrozelfist/3proxy-openwrt package/net/3proxy
        # git clone https://github.com/v2rayA/v2raya-openwrt package/net/v2raya

    - name: Pre-feeds
      run: |          
        # mkdir -p ./firmware/i915
        # curl -L https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/plain/i915/icl_dmc_ver1_09.bin -o ./firmware/i915/icl_dmc_ver1_09.bin
        # echo 'CONFIG_FIRMWARE_IN_KERNEL=y' >> ./target/linux/x86/64/config-5.15
        # echo 'CONFIG_EXTRA_FIRMWARE="i915/glk_dmc_ver1_04.bin"' >> ./target/linux/x86/64/config-5.15
        # echo 'CONFIG_EXTRA_FIRMWARE_DIR="./firmware"' >> ./target/linux/x86/64/config-5.15

    - name: Update & Install feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        ./scripts/feeds install -a

    - name: Post-feeds
      run: |
        # sed -i '/DEFAULT:=n/d' feeds/packages/net/rp-pppoe/Makefile

    - name: Generate configuration file
      run: |
        ver=$(echo ${{ env.tag }} | cut -c 2-)
        rm -f ./.config*
        curl https://downloads.immortalwrt.org/releases/$ver/targets/x86/64/config.buildinfo | grep -e _TARGET_ -e _PACKAGE_ -e _VERSION_ >> ./.config
        sed -i 's/CONFIG_TARGET_MULTI_PROFILE=y/CONFIG_TARGET_MULTI_PROFILE=n/' ./.config
        sed -i 's/CONFIG_TARGET_PER_DEVICE_ROOTFS=y/CONFIG_TARGET_PER_DEVICE_ROOTFS=n/' ./.config
        sed -i 's/CONFIG_TARGET_ALL_PROFILES=y/CONFIG_TARGET_ALL_PROFILES=n/' ./.config
        echo CONFIG_KERNEL_BUILD_DOMAIN="Azure" >> ./.config
        echo CONFIG_KERNEL_BUILD_USER="OpenWrt-CI" >> ./.config

        cat >> .config <<EOF
        CONFIG_TARGET_ROOTFS_TARGZ=n
        CONFIG_TARGET_ROOTFS_SQUASHFS=n
        EOF

        cat >> .config <<EOF
        CONFIG_PACKAGE_base-files=y
        CONFIG_PACKAGE_bash=y
        CONFIG_PACKAGE_block-mount=y
        CONFIG_PACKAGE_busybox=y
        CONFIG_PACKAGE_ca-bundle=y
        CONFIG_PACKAGE_coremark=y
        CONFIG_PACKAGE_curl=y
        CONFIG_PACKAGE_dnsmasq-full=y
        CONFIG_PACKAGE_dropbear=y
        CONFIG_PACKAGE_ds-lite=y
        CONFIG_PACKAGE_e2fsprogs=y
        CONFIG_PACKAGE_fdisk=y
        CONFIG_PACKAGE_firewall4=y
        CONFIG_PACKAGE_fstools=y
        CONFIG_PACKAGE_htop=y
        CONFIG_PACKAGE_kmod-8139cp=y
        CONFIG_PACKAGE_kmod-8139too=y
        CONFIG_PACKAGE_kmod-atlantic=y
        CONFIG_PACKAGE_kmod-bnx2=y
        CONFIG_PACKAGE_kmod-bnx2x=y
        CONFIG_PACKAGE_kmod-button-hotplug=y
        CONFIG_PACKAGE_kmod-e1000=y
        CONFIG_PACKAGE_kmod-forcedeth=y
        CONFIG_PACKAGE_kmod-fs-vfat=y
        CONFIG_PACKAGE_kmod-i40e=y
        CONFIG_PACKAGE_kmod-iavf=y
        CONFIG_PACKAGE_kmod-igb=y
        CONFIG_PACKAGE_kmod-igc=y
        CONFIG_PACKAGE_kmod-ixgbe=y
        CONFIG_PACKAGE_kmod-ixgbevf=y
        CONFIG_PACKAGE_kmod-lib-zstd=y
        CONFIG_PACKAGE_kmod-mlx4-core=y
        CONFIG_PACKAGE_kmod-mlx5-core=y
        CONFIG_PACKAGE_kmod-mmc=y
        CONFIG_PACKAGE_kmod-pcnet32=y
        CONFIG_PACKAGE_kmod-phy-broadcom=y
        CONFIG_PACKAGE_kmod-r8101=y
        CONFIG_PACKAGE_kmod-r8125=y
        CONFIG_PACKAGE_kmod-r8126=y
        CONFIG_PACKAGE_kmod-r8168=y
        CONFIG_PACKAGE_kmod-sdhci=y
        CONFIG_PACKAGE_kmod-tcp-bbr=y
        CONFIG_PACKAGE_kmod-tg3=y
        CONFIG_PACKAGE_kmod-tulip=y
        CONFIG_PACKAGE_kmod-usb-hid=y
        CONFIG_PACKAGE_kmod-vmxnet3=y
        CONFIG_PACKAGE_libc=y
        CONFIG_PACKAGE_lm-sensors-detect=y
        CONFIG_PACKAGE_logd=y
        CONFIG_PACKAGE_lsblk=y
        CONFIG_PACKAGE_luci-app-alist=y
        CONFIG_PACKAGE_luci-app-argon-config=y
        CONFIG_PACKAGE_luci-app-aria2=y
        CONFIG_PACKAGE_luci-app-arpbind=y
        CONFIG_PACKAGE_luci-app-autoreboot=y
        CONFIG_PACKAGE_luci-app-cpulimit=y
        CONFIG_PACKAGE_luci-app-diskman=y
        CONFIG_PACKAGE_luci-app-eqos=y
        CONFIG_PACKAGE_luci-app-filemanager=y
        CONFIG_PACKAGE_luci-app-firewall=y
        CONFIG_PACKAGE_luci-app-hd-idle=y
        CONFIG_PACKAGE_luci-app-lxc=y
        CONFIG_PACKAGE_luci-app-msd_lite=y
        CONFIG_PACKAGE_luci-app-mwan3=y
        CONFIG_PACKAGE_luci-app-netdata=y
        CONFIG_PACKAGE_luci-app-nlbwmon=y
        CONFIG_PACKAGE_luci-app-p910nd=y
        CONFIG_PACKAGE_luci-app-package-manager=y
        CONFIG_PACKAGE_luci-app-qbittorrent=y
        CONFIG_PACKAGE_luci-app-qos=y
        CONFIG_PACKAGE_luci-app-ramfree=y
        CONFIG_PACKAGE_luci-app-smartdns=y
        CONFIG_PACKAGE_luci-app-syncdial=y
        CONFIG_PACKAGE_luci-app-ttyd=y
        CONFIG_PACKAGE_luci-app-uhttpd=y
        CONFIG_PACKAGE_luci-app-upnp=y
        CONFIG_PACKAGE_luci-app-vlmcsd=y
        CONFIG_PACKAGE_luci-app-watchcat=y
        CONFIG_PACKAGE_luci-app-wifischedule=y
        CONFIG_PACKAGE_luci-app-wol=y
        CONFIG_PACKAGE_luci-base=y
        CONFIG_PACKAGE_luci-compat=y
        CONFIG_PACKAGE_luci-lib-ipkg=y
        CONFIG_PACKAGE_mkf2fs=y
        CONFIG_PACKAGE_mtd=y
        CONFIG_PACKAGE_nano=y
        CONFIG_PACKAGE_netifd=y
        CONFIG_PACKAGE_odhcp6c=y
        CONFIG_PACKAGE_odhcpd-ipv6only=y
        CONFIG_PACKAGE_openssh-sftp-server=y
        CONFIG_PACKAGE_opkg=y
        CONFIG_PACKAGE_partx-utils=y
        CONFIG_PACKAGE_pciutils=y
        CONFIG_PACKAGE_ppp=y
        CONFIG_PACKAGE_ppp-mod-pppoe=y
        CONFIG_PACKAGE_procd=y
        CONFIG_PACKAGE_procd-seccomp=y
        CONFIG_PACKAGE_resolveip=y
        CONFIG_PACKAGE_swconfig=y
        CONFIG_PACKAGE_uci=y
        CONFIG_PACKAGE_uclient-fetch=y
        CONFIG_PACKAGE_urandom-seed=y
        CONFIG_PACKAGE_urngd=y
        CONFIG_PACKAGE_usbutils=y
        CONFIG_PACKAGE_wget-ssl=y
        CONFIG_PACKAGE_zram-swap=y
        CONFIG_PACKAGE_luci-app-accesscontrol-plus=y
        CONFIG_PACKAGE_luci-app-adguardhome=y
        CONFIG_PACKAGE_luci-app-aria2=y
        CONFIG_PACKAGE_luci-app-alist=y
        CONFIG_PACKAGE_luci-app-autotimeset=y
        CONFIG_PACKAGE_luci-app-cpulimit=y
        CONFIG_PACKAGE_luci-app-diskman=y
        CONFIG_PACKAGE_luci-app-hd-idle=y
        CONFIG_PACKAGE_luci-app-homebox=y
        CONFIG_PACKAGE_luci-app-iptvhelper=y
        CONFIG_PACKAGE_luci-app-msd_lite=y
        CONFIG_PACKAGE_luci-app-netdata=y
        CONFIG_PACKAGE_luci-app-nlbwmon=y
        CONFIG_PACKAGE_luci-app-oaf=y
        CONFIG_PACKAGE_luci-app-netspeedtest=y
        CONFIG_PACKAGE_luci-app-p910nd=y
        CONFIG_PACKAGE_luci-app-partexp=y
        CONFIG_PACKAGE_luci-app-qos=y
        CONFIG_PACKAGE_luci-app-ramfree=y
        CONFIG_PACKAGE_luci-app-syncdial=y
        CONFIG_PACKAGE_luci-app-turboacc=y
        CONFIG_PACKAGE_luci-app-ttyd=y
        CONFIG_PACKAGE_luci-app-timedreboot=y
        CONFIG_PACKAGE_luci-app-vlmcsd=y
        CONFIG_PACKAGE_luci-app-apfree-wifidog=y
        CONFIG_PACKAGE_luci-app-wifischedule=y
        CONFIG_PACKAGE_luci-app-watchcat=y
        CONFIG_PACKAGE_luci-app-argon-config=y
        CONFIG_PACKAGE_autocore=y
        CONFIG_PACKAGE_base-files=y
        CONFIG_PACKAGE_bash=y
        CONFIG_PACKAGE_block-mount=y
        CONFIG_PACKAGE_busybox=y
        CONFIG_PACKAGE_ca-bundle=y
        CONFIG_PACKAGE_coremark=y
        CONFIG_PACKAGE_curl=y
        CONFIG_PACKAGE_dnsmasq-full=y
        CONFIG_PACKAGE_dropbear=y
        CONFIG_PACKAGE_ds-lite=y
        CONFIG_PACKAGE_e2fsprogs=y
        CONFIG_PACKAGE_fdisk=y
        CONFIG_PACKAGE_firewall4=y
        CONFIG_PACKAGE_fstools=y
        CONFIG_PACKAGE_grub2-bios-setup=y
        CONFIG_PACKAGE_htop=y
        CONFIG_PACKAGE_kmod-8139cp=y
        CONFIG_PACKAGE_kmod-8139too=y
        CONFIG_PACKAGE_kmod-amazon-ena=y
        CONFIG_PACKAGE_kmod-amd-xgbe=y
        CONFIG_PACKAGE_kmod-atlantic=y
        CONFIG_PACKAGE_kmod-bnx2=y
        CONFIG_PACKAGE_kmod-bnx2x=y
        CONFIG_PACKAGE_kmod-button-hotplug=y
        CONFIG_PACKAGE_kmod-drm-amdgpu=y
        CONFIG_PACKAGE_kmod-drm-i915=y
        CONFIG_PACKAGE_kmod-dwmac-intel=y
        CONFIG_PACKAGE_kmod-e1000=y
        CONFIG_PACKAGE_kmod-e1000e=y
        CONFIG_PACKAGE_kmod-forcedeth=y
        CONFIG_PACKAGE_kmod-fs-vfat=y
        CONFIG_PACKAGE_kmod-i40e=y
        CONFIG_PACKAGE_kmod-iavf=y
        CONFIG_PACKAGE_kmod-igb=y
        CONFIG_PACKAGE_kmod-igbvf=y
        CONFIG_PACKAGE_kmod-igc=y
        CONFIG_PACKAGE_kmod-ixgbe=y
        CONFIG_PACKAGE_kmod-ixgbevf=y
        CONFIG_PACKAGE_kmod-lib-zstd=y
        CONFIG_PACKAGE_kmod-mlx4-core=y
        CONFIG_PACKAGE_kmod-mlx5-core=y
        CONFIG_PACKAGE_kmod-mmc=y
        CONFIG_PACKAGE_kmod-pcnet32=y
        CONFIG_PACKAGE_kmod-phy-broadcom=y
        CONFIG_PACKAGE_kmod-r8101=y
        CONFIG_PACKAGE_kmod-r8125=y
        CONFIG_PACKAGE_kmod-r8126=y
        CONFIG_PACKAGE_kmod-r8168=y
        CONFIG_PACKAGE_kmod-sdhci=y
        CONFIG_PACKAGE_kmod-tcp-bbr=y
        CONFIG_PACKAGE_kmod-tg3=y
        CONFIG_PACKAGE_kmod-tulip=y
        CONFIG_PACKAGE_kmod-usb-hid=y
        CONFIG_PACKAGE_kmod-vmxnet3=y
        CONFIG_PACKAGE_libc=y
        CONFIG_PACKAGE_libgcc=y
        CONFIG_PACKAGE_libustream-mbedtls=y
        CONFIG_PACKAGE_lm-sensors-detect=y
        CONFIG_PACKAGE_logd=y
        CONFIG_PACKAGE_lsblk=y
        CONFIG_PACKAGE_luci-app-advancedplus=y
        CONFIG_PACKAGE_luci-app-fan=y
        CONFIG_PACKAGE_luci-app-filemanager=y
        CONFIG_PACKAGE_luci-app-firewall=y
        CONFIG_PACKAGE_luci-app-package-manager=y
        CONFIG_PACKAGE_luci-app-syscontrol=y
        CONFIG_PACKAGE_luci-app-upnp=y
        CONFIG_PACKAGE_luci-app-wizard=y
        CONFIG_PACKAGE_luci-base=y
        CONFIG_PACKAGE_luci-compat=y
        CONFIG_PACKAGE_luci-lib-fs=y
        CONFIG_PACKAGE_luci-lib-ipkg=y
        CONFIG_PACKAGE_mkf2fs=y
        CONFIG_PACKAGE_mtd=y
        CONFIG_PACKAGE_nano=y
        CONFIG_PACKAGE_netifd=y
        CONFIG_PACKAGE_odhcp6c=y
        CONFIG_PACKAGE_odhcpd-ipv6only=y
        CONFIG_PACKAGE_openssh-sftp-server=y
        CONFIG_PACKAGE_opkg=y
        CONFIG_PACKAGE_partx-utils=y
        CONFIG_PACKAGE_pciutils=y
        CONFIG_PACKAGE_ppp=y
        CONFIG_PACKAGE_ppp-mod-pppoe=y
        CONFIG_PACKAGE_procd=y
        CONFIG_PACKAGE_procd-seccomp=y
        CONFIG_PACKAGE_resolveip=y
        CONFIG_PACKAGE_swconfig=y
        CONFIG_PACKAGE_uci=y
        CONFIG_PACKAGE_uclient-fetch=y
        CONFIG_PACKAGE_urandom-seed=y
        CONFIG_PACKAGE_urngd=y
        CONFIG_PACKAGE_usbutils=y
        CONFIG_PACKAGE_wget-ssl=y
        CONFIG_PACKAGE_zram-swap=y
        CONFIG_PACKAGE_luci-app-poweroff=y
        CONFIG_PACKAGE_luci-app-filetransfer=y
        CONFIG_PACKAGE_luci-app-autoreboot=y
        CONFIG_PACKAGE_luci-app-pushbot=y
        CONFIG_PACKAGE_luci-app-smartdns=y
        CONFIG_PACKAGE_luci-app-wol=y
        CONFIG_PACKAGE_luci-app-lxc=y
        CONFIG_PACKAGE_luci-app-uhttpd=y
        CONFIG_PACKAGE_luci-app-qbittorrent=y
        CONFIG_PACKAGE_luci-app-arpbind=y
        CONFIG_PACKAGE_luci-app-eqos=y
        CONFIG_PACKAGE_luci-app-mwan3=y
        CONFIG_PACKAGE_ipv6helper=y
        CONFIG_PACKAGE_lucky=y
        EOF

        make defconfig

    - name: Download package
      working-directory: ./openwrt
      run: |
        make download -j$(nproc)
        rm -rf $(find ./dl/ -size -1024c)

    - name: Build firmware
      working-directory: ./openwrt
      run: |
        echo -e "$(nproc) thread build."
        make -j$(nproc) V=s

    - name: Prepare artifact
      run : |
        mkdir -p ./artifact/firmware
        mkdir -p ./artifact/package
        mkdir -p ./artifact/buildinfo
        rm -rf $(find ./bin/targets/ -type d -name "packages")
        cp -rf $(find ./bin/targets/ -type f) ./artifact/firmware/
        cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/package/
        cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifact/buildinfo/

        # rm -rf $(find ./artifact/firmware/ -type f -name "*.tar.gz")
        rm -rf $(find ./artifact/firmware/ -type f -name "*.bin")
        rm -rf $(find ./artifact/firmware/ -type f -name "*.img*" | grep -v "combined-efi")

    - name: Deliver buildinfo
      uses: actions/upload-artifact@v4
      with:
        name: buildinfo_${{ env.tag }}_${{ env.sha }}
        path: ./artifact/buildinfo/

    - name: Deliver package
      uses: actions/upload-artifact@v4
      with:
        name: package_${{ env.tag }}_${{ env.sha }}
        path: ./artifact/package/

    - name: Deliver firmware
      uses: actions/upload-artifact@v4
      with:
        name: firmware_${{ env.tag }}_${{ env.sha }}
        path: ./artifact/firmware/
